<?php

$op = $this->operatore;

echo '
    <div class="container">
    
    <div class="left-align">
    <div class="image">
                                                 ' .$this->imgProfilo($op->fotoprofilo) .'
                                 
                                        </div>
    <h3 class="center-align blue-text"><b>' .$op->nome . ' ' . $op->cognome .  '</b></h3>
    <div class="col s6" >
        <ul class="collection">
            <li class="collection-item"><b>Città:</b> ' .$op->citta. '</li>
            <li class="collection-item">
                                            <p class="black-text"><b>Indirizzo:</b> ' .$op->indirizzo. ' </p>
                                            </li>
                                                                                        <li class="collection-item">
                                            <p class="black-text"><b>Disponibilità:</b> ' .$op->disp. ' </p>
                                            </li>
                                            <li class="collection-item">
                                            <p class="black-text"><b>Descrizione:</b> ' .$op->descrizione. ' </p>
                                            </li>
                                            <li class="collection-item">
                                            <p class="black-text"><b>Ente di rilascio attestato:</b> ' .$op->ente. ' </p>
                                            </li>
                                            <li class="collection-item">
                                            <p class="black-text"><b>Email:</b> ' .$op->email. ' </p>
                                            </li>
                                            <li class="collection-item">
                                            <p class="green-text"><b>Tariffa oraria:</b> ' .$op->prezzo. '€</p>
                                            </li>
        </ul>
    </div>
   


    <div class="right">
        <td class="modifica">
            <a  class="btn orange" onclick="allerta()">Modifica Profilo</a>
        </td>
    </div>
</div>
'?>

<script>
    function allerta() {
        window.alert("QUESTA E UNA DEMO");
    }
</script>


