

<div class="container center">
    <div>
        <br>
        <h2 class="teal-text deep-orange-text">Benvenuto nel tuo profilo</h2>
        <h2 class="text-darken-1"><i><?php echo $this -> authInfo('nome') . ' ' . $this -> authInfo('cognome'); ?></i></h2>
        <div class="image center-block">
                <?= $this->imgProfilo($this -> authInfo('fotoprofilo')); ?>
        </div>
        <h4 class ="teal-text deep-orange-text"> Email:</h4> <h4 class ="text-darken-1"><?php echo $this -> authInfo('email'); ?> </h4>
        <h4 class="teal-text deep-orange-text"> <i>Prezzo:</h4> <h4 class ="text-darken-1"> <?php echo $this -> authInfo('prezzo'); ?></i></h4>
        <h4 class="teal-text deep-orange-text"> <i>Password:</h4> <h4 class ="text-darken-1"> <?php echo $this -> authInfo('password'); ?></i></h4>
        <h4 class ="teal-text deep-orange-text"> Valutazioni:</h4>

    </div>
    <br>
    <div class="left">
        <td class="modifica">
            <a  class="btn orange" onclick="allerta()">Modifica Profilo</a>
        </td>
    </div>
</div>


<script>
    function allerta() {
        window.alert("QUESTA E' UNA DEMO");
    }
</script>


