<div class="container">
    <br><br>
    <h2 class="header center green-text">FreeBlog</h2>
    <h4 class="header center green-text">Accedi, aggiungi i tuoi amici e scrivi!</h4>
    <p class="center"><b>FreeBlog è una comunità on-line nata con l'obiettivo di incentivare lo scambio di idee e la condivisione di
        opinioni su temi di ogni genere.</b></p>
    <br><br>
    <h5 class="green-text">Unisciti a FreeBlog</h5>
    <p>Per entrare a far parte della community è necessario registrarsi al sito: inserisci i tuoi dati anagrafici
        e scegli username e password per eseguire l'accesso.</p>
    <p>Se non sei ancora iscritto <a href="<?= $this->url(array(
            'controller' => 'public',
            'action' => 'registrazione'),
            'default',true
        );
        ?>" title ="Iscriviti a FreeBlog">registrati ora.</a></p>
    <p>Se invece sei già iscritto inserisci il tuo username e la tua password ed
        <a href="<?= $this->url(array(
            'controller' => 'public',
            'action' => 'login'),
            'default',true
        );
        ?>" title ="Accedi">effettua il login.</a>
    </p>
    <br>
    <h5 class="green-text">Aggiungi i tuoi amici</h5>
    <p>Una volta eseguito l'accesso potrai controllare se un'altra persona è iscritta a FreeBlog. Per aggiungere
        una persona basterà inviarle una richiesta: se il destinatario di tale richiesta la accetterà, allora
        diventerete amici su FreeBlog. Inizia subito a formare il tuo gruppo di amici e visita i loro profili!</p>
    <br>
    <h5 class="green-text">Crea i tuoi blog</h5>
    <p>Potrai anche creare i tuoi blog personali: scegli l'argomento e inizia a condividere i tuoi pensieri!</p>
    <p>Non solo: le persone che appartengono al tuo gruppo di amici potranno commentare ciò che scrivi
        postando le loro risposte direttamente sul tuo blog. E anche tu puoi fare lo stesso: visita i blog dei tuoi amici
        e posta le tue idee.</p>
    <br><br>
</div>