<div class="container">
    <br><br>
    <h4 class="header center green-text">Normative di FreeBlog</h4>
    <br><br>	
    <h5 class="red-text">Privacy</h5>
    <ol>
        <li>Ciascun utente iscritto può decidere se rendersi visibile a tutti o solo al sotto-insieme
            della comunità costituito dagli utenti suoi amici; in quest'ultimo caso, ai non amici sono visibili
            solamente nome e cognome dell'utente;</li>
        <li>Se un utente vuole aggiungere una persona al proprio gruppo di amici, deve inviargli una richiesta; l'utente
            che la riceve può accettarla o rifiutarla. Solo se accetta la richiesta, i due utenti diventano amici.
            In tal caso ognuno dei due ha accesso alle informazioni, profilo e blog dell'altro;</li>
        <li>Ogni utente può inviare e accettare/rifiutare richieste di amicizia. Può inoltre eliminare dal gruppo dei suoi amici
            chiunque quando vuole; l’utente eliminato riceve un messaggio di notifica;</li>
        <li>Ciascun utente può accedere, sia in lettura che in scrittura, ai blog degli utenti suoi amici.
            Ogni volta che un post viene aggiunto ad un blog, tutti coloro che vi hanno accesso ricevono una notifica.</li>
    </ol>
    <br>
    <h5 class ="red-text">Standard della comunità</h5>
    <p>L'amministratore e lo staff di FreeBlog hanno accesso ai blog di tutti gli utenti e possono cancellare
        interi blog o singoli post ritenuti non in linea con il comportamento stabilito per i membri della comunità.
        Ad ogni cancellazione corrisponde l’invio di un messaggio a chi ha inserito l’oggetto cancellato
        con l’indicazione del motivo dell’azione.</p>
    <p>Lo staff può intervenire qualora vengano riscontrati:</p>
    <ol>
        <li>Contenuti che incitano all'odio o alla violenza;</li>
        <li>Contenuti volgari o blasfemi;</li>
        <li>Contenuti che presentano forme di discriminazione;</li>
        <li>Contenuti che presentano minacce o intimidazioni.</li>
    </ol>
    <p>Qualora lo ritenga necessario, l'amministratore ha la facoltà di eliminare i membri della comunità.</p>
    <br><br>
</div>
