<div class="container ">
    <img src="<?= $this->baseUrl('images/sfondo.jpg')?>" id="backgroundimage" border="0" alt="">
    <div class="row" id="card-container">
        <div class="col s9 pull-l2">
            <div class="card blue lighten-1">
                <div class="card-content white-text">
                    <span class="card-title">
                        <h4>Assistenza Sanitaria</h4>
                        <p>Trova il libero professionista più vicino a te.</p>
                    </span>
                </div>
                <div class="card-action">
                    <p class="white-text card-title">Cosa stai cercando?</p>
                    <a class="card-title" href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'operatori',
                        'tipo' => 'Infermiere'
                        ),
                        'default',true
                    );
                    ?>"><b>Infermiere</b></a><br>
                    <a class="card-title" href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'operatori',
                        'tipo' => 'Operatore Socio Sanitario'
                        ),
                        'default',true
                    );
                    ?>"><b>Operatore Socio Sanitario</b></a><br>
                    <a class="card-title" href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'operatori',
                        'tipo' => 'Fisioterapista'
                        ),
                        'default',true
                    );
                    ?>"><b>Fisioterapista</b></a>
                </div>
            </div>
        </div>
    </div>
</div>
