<div class="container ">
    <img src="<?= $this->baseUrl('images/sfondo.jpg')?>" id="backgroundimage" border="0" alt="">
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <div class="row">
        <div class="col s9 pull-l2">
            <div class="card small blue lighten-2">
                <div class="card-content white-text">
                    <span class="card-title">
                        <h3>Assistenza Sanitaria</h3>
                        <p>Trova il libero professionista più vicino a te.</p>
                    </span>
                </div>
                <div class="card-action">
                    <p class="white-text">Cosa stai cercando?</p>
                    <a href="#">Infermiere</a>
                    <a href="#">Operatore Socio Sanitario</a>
                    <a href="#">Fisioterapista</a>
                </div>
            </div>
        </div>
    </div>
</div>
