




<div class="container">
    <img style="opacity: 0.5" class ="img-responsive" src="<?= $this->baseUrl('images/sfondo1.jpg')?>" id="backgroundimage" border="0" alt="">

    <div style="display: flex; margin-top: 7%" id="card-container">

            <div class="container right" >
                <div style="width: 100%; height: 100%; float: left; padding-right: 10%; border-right-color: darkred; border-right-width: 1 px;border-right-style: solid;" class="card-content red-text text-darken-4">

                        <h4>HAI BISOGNO DI PRESTAZIONI MEDICHE A DOMICILIO?</h4>
                        <h6>Con <b>Assistenza Sanitaria</b> trovi il professionista più vicino a te 7 giorni su 7, 24 ore su 24.</h6>

                    <br>
                    <p class=" center red-text text-darken-4">Quale figura professionale stai cercando?</p>

                    <div class="row">


                        <a style="display: block" class="center blue darken-4 waves-effect waves-light btn" href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'operatori',
                        'tipo' => 'Infermiere'
                        ),
                        'default',true
                    );
                    ?>">Infermiere</a><br>
                    <a style="display: block" class=" blue darken-4 waves-effect waves-light btn" href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'operatori',
                        'tipo' => 'Operatore Socio Sanitario'
                        ),
                        'default',true
                    );
                    ?>">OSS</a><br>
                    <a style="display: block" class="blue darken-4 waves-effect waves-light btn" href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'operatori',
                        'tipo' => 'Fisioterapista'
                        ),
                        'default',true
                    );
                    ?>">Fisioterapista</a>
                </div>
            </div>
            </div>

        <div class="container left">
            <div style="width: 100%; height: 100%; float: right; padding-left: 10%;" class="card-content red-text text-darken-4">
                <h4>SEI UN PROFESSIONISTA IN AMBITO SANITARIO?</h4>
                <h6>Registrati al sito e metti le tue competenze al servizio di altri</h6>
                <br>
                <div class="center container">
                    <a href="
                        <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'registrazioneoperatore'
                    ),
                        'default',true
                    );
                    ?>"
                            class="center white blue-text text-darken-4 darken-4 waves-effect waves-light btn large">Fornisci assistenza</a>
                </div>
            </div>
        </div>
</div>


