<div class="container">
    <br><br>
    <div>
        <table>
            <?php

            if ($this->operatori== NULL) {
                echo '<h3 class="blue-text">Spiacenti, nessun professionista trovato per questa categoria.</h3>';
            }

            else {

                echo '<h4 class="blue-text darken-2">Professionisti trovati nella categoria: <b>' . $this->tipo . '</b></h4>';
                foreach ($this->operatori as $op) {
                    echo '<tr>
                                  <td><div class="image">' .$this->imgProfilo($op->fotoprofilo, array('class' => 'circle imagefrmsearch')).'</div></td>
                                  <td><a href=' . $this->url(array(
                            'controller' => 'public',
                            'action' => 'index'),
                            'default', true) .
                        '>' . $op->nome . ' ' . $op->cognome . '</a></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                             </tr>';
                }
            }
            ?>
        </table>
    </div>
</div>
