<div class="container">
    <h3 class="blue-text">Operatori cercati DA CAMBIARE</h3>
    <div>
        <table>
            <?php
            if ($this->operatori == NULL) {
                echo '<p>Nessun professionista trovato.</p>';
            }
            else {
                foreach ($this->operatori as $op) {
                    echo '<tr>
                                  
                            <td><a href=' . $this->url(array(
                            'controller' => 'user',
                            'action' => 'alias',
                            'utenteUsername' => $utente->username),
                            'default', true) .
                        '>' . $op->nome . ' ' . $op->cognome . '</a></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                             </tr>';
                }
            }
            ?>
        </table>
    </div>
</div>
