<div class="container">
    <br><br>
    <h4 class="header center orange-text">Complimenti!</h4>
    <p class="center">La registrazione è avvenuta con successo.</p>
    <p class="center">Per effettuare l'accesso clicca su <a href="
        <?= $this->url(array(
            'controller' => 'public',
            'action'     => 'login'),
            'default',true
        );
        ?>">Login</a>.</p>
    <br><br>
</div>
