<div class="container">
    <br><br><br><br><br><br>
    <h4 class="header center blue-text">Regolamento del sito</h4>
    <br>
    <p class="center"><b>Assistenza Anziani</b> è un sito web nato con l'obiettivo di farti trovare il libero professionista
    per la cura degli anziani più vicino a te. </p><p class="center">Puoi stare tranquillo! Per tutti i professionisti registrati sono previsti meccanismi di
        verifica del loro curriculum e delle loro competenze.</p>
    <br><br><br>
    <h5 class="red-text">Cerchi un professionista?</h5>
    <br>
    <p>Su Assistenza Anziani ci sono infermieri, operatori socio sanitari e
    fisioterapisti a disposizione per le tue esigenze.</p>
    <p>Trova il tuo professionista, scegli il servizio di cui hai bisogno e dopo aver effettuato il pagamento potrai metterti
    in contatto con lui.</p>
    <p>Dopo aver ricevuto la prestazione, potrai valutarla inviando un feedback visibile a tutti: in questa maniera aiuti anche
    gli altri membri nella scelta della loro figura professionale!</p>
    <br><br>
    <h5 class="red-text">Sei un libero professionista e cerchi lavoro?</h5>
    <br>
    <p>Registrati al sito, pubblica il tuo curriculum e scegli i servizi che offri: in questa maniera sarai contattato dagli utenti registrati.</p>
    <p>Inizia adesso: è gratis!</p>
    <br><br><br><br><br><br>
    <h5 class="center red-text">Contatti:</h5>
    <p class="center">Telefono: 871/2345678</p>
    <p class="center">E-mail: <a href="mailto: assistenzaanziani@gmail.com">assistenzaanziani@gmail.com</a></p>
</div>
