<div class="container">
    <br><br>
    <h4 class="header center orange-text">Su di noi</h4>
    <br>
    <p class="center">FreeBlog è un portale sviluppato dalla <b>Paciotty Enterprises</b>.</p>
    <p class="center"><b>Paciotty Enterprises</b> è un'azienda nata nel 2005. Da oltre dieci anni ci occupiamo della realizzazione e
        manutenzione di infrastrutture web. Siamo costantemente al lavoro per il miglioramento e l'aggiornamento
        dei nostri servizi, per garantire al cliente un'esperienza fresca e sicura.</p>
    <br><br><br>
    <h5 class="center orange-text">Contatti:</h5>
    <p class="center">Telefono: 8736/333444</p>
    <p class="center">E-mail: <a href="mailto: freeblog@paciotty.com">freeblog@paciotty.com</a></p>
    <br><br>
</div>
