<ul>
    <a id="logo-container"
       class="brand-logo"
       href="
                <?= $this->url(array(
           'controller' => 'operatore',
           'action'     => 'index'
       ),
           'default',true
       );
       ?>"
       title="Home"><img class="" src="<?= $this->baseUrl('images/assistenza_anziani.png')?>" id="img-logo" >Assistenza Sanitaria</a>
    <ul class="right" id="logo-container">
        <li></li>
        <li></li>
        <li></li>
        <li><a href="
                        <?= $this->url(array(
                'controller' => 'operatore',
                'action'     => 'viewstatic',
                'staticPage' => 'rules'
            ),
                'default',true
            );
            ?>"
               title="Scopri la nostra azienda">Regolamento</a></li>
        <li><a href="
                        <?= $this->url(array(
                'controller' => 'public',
                'action'     => 'index'
            ),
                'default',true
            );
            ?>"
               title="Effettua il logout">Logout</a></li>
    </ul>
</ul>