<ul>
    <a id="logo-container"
       class="brand-logo"
       href="
                <?= $this->url(array(
           'controller' => 'public',
           'action'     => 'index'
       ),
           'default',true
       );
       ?>"
       title="Home"><img class="" src="<?= $this->baseUrl('images/assistenza_anziani.jpg')?>" id="img-logo" >Assistenza Anziani</a>
    <ul class="right">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li><a href="
                        <?= $this->url(array(
                'controller' => 'public',
                'action'     => 'login'
            ),
                'default',true
            );
            ?>"
               title="Effettua il login">Login</a></li>
        <li><a href="
                        <?= $this->url(array(
                'controller' => 'public',
                'action'     => 'registrazione'
            ),
                'default',true
            );
            ?>"
               title="Registrati è gratis">Registrazione</a></li>
    </ul>
</ul>