<!DOCTYPE html>
<head>
    <?= $this->headMeta(); ?>
    <?= $this->headLink(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->headScript(); ?>
</head>
<body id="wrap">
<div>

    <nav class="green">
        <div class="container">
            <?= $this->render('_topnavmain.phtml') ?>
        </div>
    </nav>

    <div class="section no-pad-bot" id="main">
        <?php echo $this->layout()->content; ?>
    </div>

    <footer class="page-footer green" id="footer">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="orange-text">FreeBlog</h5>
                    <p class="no-margin grey-text text-lighten-2 small-text">Visita subito i blog dei tuoi amici.</p>
                    <p class="no-margin grey-text text-lighten-2 small-text">Leggi le
                        <a class="white-text text-lighten-2 small-text" href="<?= $this->url(array(
                            'controller' => 'public',
                            'action'     => 'viewstatic',
                            'staticPage' => 'conditions'
                        ),
                            'default',true
                        );
                        ?>">Condizioni d'uso.</a></p>
                </div>
                <div class="col l6 s12 push-l2">
                    <h5 class="orange-text">Contattaci</h5>
                    <p class="no-margin grey-text text-lighten-2 small-text">Telefono: 8736/333444</p>
                    <p class="no-margin grey-text text-lighten-2 small-text">E-mail: <a class="white-text text-lighten-2 small-text" href="mailto: freeblog@paciotty.com">freeblog@paciotty.com</a></p>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container small-text">
                Progetto didattico extra-corso gruppo 57
            </div>
        </div>
    </footer>

</div>



<!--  Scripts-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="js/materialize.js"></script>
<script src="js/init.js"></script>

</body>
</html>
