<!DOCTYPE html>
<head>
    <?= $this->headMeta(); ?>
    <?= $this->headLink(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->headScript(); ?>
</head>
<body id="wrap">
<div>

    <nav class="green">
        <div class="container">
            <?= $this->render('_topnavmain.phtml') ?>
        </div>
    </nav>

    <div class="section no-pad-bot" id="main">
        <?php echo $this->layout()->content; ?>
    </div>

    <footer class="page-footer green" id="footer">
    </footer>

</div>



<!--  Scripts-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="js/materialize.js"></script>
<script src="js/init.js"></script>

</body>
</html>
