<div class="container">
    <img style="opacity: 0.5" class ="img-responsive" src="<?= $this->baseUrl('images/sfondo1.jpg')?>" id="backgroundimage" border="0" alt="">

    <div style="display: flex; margin-top: 5%; margin-bottom: 1%" id="card-container">

        <div class="container right" >
            <div style="width: 100%; height: 100%; float: left; padding-right: 10%; border-right-color: darkred; border-right-width: 1 px;" class="card-content red-text text-darken-4">

                <?php echo '<h4>Benvenuto ' . $this->utente->nome . '.</h4>' ?>


                <br>
                <p class=" center red-text text-darken-4">Quale figura professionale stai cercando?</p>

                <div class="row">


                    <a style="display: block" class="center blue darken-4 waves-effect waves-light btn" href="
                <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'operatori',
                        'tipo' => 'Infermiere'
                    ),
                        'default',true
                    );
                    ?>">Infermiere</a><br>
                    <a style="display: block" class=" blue darken-4 waves-effect waves-light btn" href="
                <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'operatori',
                        'tipo' => 'Operatore Socio Sanitario'
                    ),
                        'default',true
                    );
                    ?>">OSS</a><br>
                    <a style="display: block" class="blue darken-4 waves-effect waves-light btn" href="
                <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'operatori',
                        'tipo' => 'Fisioterapista'
                    ),
                        'default',true
                    );
                    ?>">Fisioterapista</a>
                </div>
            </div>
        </div>
    </div>
</div>
