<div class="container">
    <br><br>
    <div>
        <table>
            <?php


            if ($this->operatori== NULL) {
                echo '<h3 class="blue-text">Spiacenti, nessun professionista trovato per questa categoria.</h3>';
            }

            else {

                echo '<h4 class="blue-text darken-2">Professionisti trovati nella categoria: <b>' . $this->tipo . '</b></h4>';

                foreach ($this->operatori as $op) {
                    echo '<tr>
                                  <td width="1%">
                                        <div class="image">
                                                 ' .$this->imgProfilo($op->fotoprofilo) .'
                                 
                                        </div>
                                  </td>
                                  <td>
                                  <div id="card" onclick="prenota()" onblur="blur()" class="card horizontal light-blue lighten-5">
                                        <div class="card-stacked">
                                        <div class="card-content">
                                        <ul>
                                        
                                            <li><h6 class="center-align blue-text"><b>' .$op->nome . ' ' . $op->cognome .  '</b></h6></li>
                                            <li>
                                            <p class="black-text"><b>Città:</b> ' .$op->citta. ' </p>
                                            </li>
                                            <li>
                                            <p class="black-text"><b>Disponibilità:</b> ' .$op->disp. ' </p>
                                            </li>
                                            <li>
                                            <p class="black-text"><b>Valutazione:</b> ' .$op->disp. ' </p>
                                            </li>
                                            <li>
                                            <p class="black-text"><b>Descrizione:</b> ' .$op->descrizione. ' </p>
                                            </li>
                                        </ul>    
                                        </div>
                                        </div>
                                            
                                  </div>
                                  
                                 </div>
                              </div>                        
                             </tr>';
                }
            }
            ?>
        </table>
    </div>
</div>

<script>

    function blur() {

        $("#card").removeClass("light-blue").addClass("blue");

    }

    function prenota() {
        window.alert("Per contattare un professionista devi aver effettuato l'accesso al sito. \nVai alla sezione Accedi oppure Registrati al sito.");
    }
</script>